#!/usr/bin/env python

# ------------------
# Ookami
# Hackers Fight Club
# ------------------

# IMPORTS
from argparse import ArgumentParser

# Configuración del parser
parser = ArgumentParser(description="Script simple para pasar binario a caracteres ascii")
parser.add_argument("payload", type=str, help="Cadena por decodificar")
parser.add_argument("--separator",'-s',type=str,help="Caracter que separa los bloques de bits")

# Parsing de argumentos
args = parser.parse_args()

# Variables
separador = args.separator
mensaje = args.payload

# Si no hay separador, separa por grupos de 8 caracteres la cadena
if separador is None:
    caracs = [mensaje[i:i+8] for i in range(0,len(mensaje),8)]
    print(''.join([chr(int(c,2)) for c in caracs]), end='')
# En caso contrario, separa la cadena por el caracter indicado
else:
    caracs = mensaje.split(separador)
    print(''.join([chr(int(c,2)) for c in caracs]), end='')
